#!/bin/bash -e
#
# S2I assemble script for the 'ansible-builder-centos7' image.
# The 'assemble' script builds your application source so that it is ready to run.
#
# For more information refer to the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

if [[ "$1" == "-h" ]]; then
	# If the 'ansible-builder-centos7' assemble script is executed with '-h' flag,
	# print the usage.
	exec /usr/libexec/s2i/usage
fi

# Restore artifacts from the previous build (if they exist).
#
if [ "$(ls /tmp/artifacts/ 2>/dev/null)" ]; then
  echo "---> Restoring build artifacts..."
  mv /tmp/artifacts/. ./
fi

echo "---> Installing application ..."
cp -Rf /tmp/src/. ./dotnet

#echo "---> Building application from source..."
#ansible-playbook /tmp/src/install.yml

#echo "---> Handling start ..."
#mkdir -p /opt/app-root/bin
#cp /tmp/src/start /opt/app-root/bin
#chmod 555 /opt/app-root/bin/start
